export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS";
export const GOOGLE_AUTH_SUCCESS = "GOOGLE_AUTH_SUCCESS";
export const GOOGLE_AUTH_FAIL = "GOOGLE_AUTH_FAIL";
export const FACEBOOK_AUTH_SUCCESS = "FACEBOOK_AUTH_SUCCESS";
export const FACEBOOK_AUTH_FAIL = "FACEBOOK_AUTH_FAIL";
export const LOGOUT = "LOGOUT";



export const GET_PRODUCT = "GET_PRODUCT";
export const FETCH = "FETCH";
export const SORT_PRODUCT = "SORT_PRODUCT";
export const SORT_PRODUCT_MEN = "SORT_PRODUCT_MEN";
export const SORT_PRODUCT_WOMEN = "SORT_PRODUCT_WOMEN";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const SHOW_CAT_ITEMS = "SHOW_CAT_ITEMS";
export const FETCH_CAT_ALL_PROD = "FETCH_CAT_ALL_PROD";
export const ADD_COMMENT = "ADD_COMMENT";
export const FETCH_CART_COMPLETE = "FETCH_CART_COMPLETE";
export const FETCH_CART_INCOMPLETE = "FETCH_CART_INCOMPLETE";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const GET_ORDER = "GET_ORDER";     

export const FETCH_COMMENTS = "FETCH_COMMENTS"; 